workflows:
  ios_appetize:
    name: iOS Appetize (Simulator)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: 16.2
      vars:
        APPETIZE_API_TOKEN: "code"  # Set in Codemagic UI
    scripts:
      - name: Install Flutter 3.35.5
        script: |
          set -euo pipefail
          FLUTTER_VERSION=3.35.5
          git clone --depth 1 -b ${FLUTTER_VERSION} https://github.com/flutter/flutter.git $CM_BUILD_DIR/flutter_${FLUTTER_VERSION} || {
            git clone --depth 1 https://github.com/flutter/flutter.git $CM_BUILD_DIR/flutter_${FLUTTER_VERSION}
            cd $CM_BUILD_DIR/flutter_${FLUTTER_VERSION}
            git fetch --tags
            git checkout ${FLUTTER_VERSION}
          }
          echo "export PATH=$CM_BUILD_DIR/flutter_${FLUTTER_VERSION}/bin:$PATH" >> $CM_ENV
          echo "export PUB_CACHE=$CM_BUILD_DIR/.pub-cache" >> $CM_ENV
          export PATH="$CM_BUILD_DIR/flutter_${FLUTTER_VERSION}/bin:$PATH"
          export PUB_CACHE="$CM_BUILD_DIR/.pub-cache"
          flutter precache --ios
      - name: Flutter clean & get
        script: |
          set -euo pipefail
          source "$CM_ENV" || true
          flutter clean
          flutter pub get
      - name: Set iOS deployment target
        script: |
          set -euo pipefail
          # Update deployment target to 15.0 (required by Firebase SDK 12.2.0)
          sed -i '' "s/platform :ios, '[0-9.]*'/platform :ios, '15.0'/g" ios/Podfile 2>/dev/null || \
          sed -i "s/platform :ios, '[0-9.]*'/platform :ios, '15.0'/g" ios/Podfile
          
          # Also update in project.pbxproj
          if [ -f ios/Runner.xcodeproj/project.pbxproj ]; then
            sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj 2>/dev/null || \
            sed -i 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj
          fi
          
          echo "✅ iOS deployment target set to 15.0"
      - name: CocoaPods install
        script: |
          set -euo pipefail
          source "$CM_ENV" || true
          if [ ! -f ios/Flutter/Generated.xcconfig ]; then
            flutter pub get
          fi
          cd ios
          # Clean pods to ensure fresh installation
          rm -rf Pods Podfile.lock .symlinks/
          pod repo update
          pod install --repo-update
          # Verify Firebase pods are installed
          if ! grep -q "FirebaseCore" Podfile.lock; then
            echo "ERROR: FirebaseCore not found in Podfile.lock"
            exit 1
          fi
          echo "✅ Firebase pods installed successfully"
      - name: Verify Firebase setup
        script: |
          set -euo pipefail
          # Check if GoogleService-Info.plist exists
          if [ ! -f ios/Runner/GoogleService-Info.plist ]; then
            echo "WARNING: GoogleService-Info.plist not found!"
            echo "Firebase will not work without this file."
          else
            echo "✅ GoogleService-Info.plist found"
          fi
          # Check AppDelegate.swift has correct imports
          if ! grep -q "import FirebaseCore" ios/Runner/AppDelegate.swift; then
            echo "ERROR: AppDelegate.swift missing 'import FirebaseCore'"
            echo "Please update AppDelegate.swift with correct Firebase imports"
            exit 1
          fi
          echo "✅ AppDelegate.swift has FirebaseCore import"
      - name: Build simulator app
        script: |
          set -euo pipefail
          source "$CM_ENV" || true
          flutter build ios --debug --simulator
      - name: Zip Runner.app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app
      - name: Upload to Appetize
        script: |
          if [ -z "$APPETIZE_API_TOKEN" ]; then
            echo "APPETIZE_API_TOKEN missing!" >&2
            exit 1
          fi
          RESPONSE=$(curl -s -X POST https://api.appetize.io/v1/apps \
            -u "$APPETIZE_API_TOKEN:" \
            -F "platform=ios" \
            -F "file=@build/ios/iphonesimulator/Runner.zip")
          echo "Appetize response: $RESPONSE"
          PUBLIC_URL=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('publicUrl',''))")
          echo "PUBLIC_URL=$PUBLIC_URL" >> $CM_ENV
          echo "Appetize URL: $PUBLIC_URL"

  ios_ipa_unsigned:
    name: iOS IPA (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: 16.2
    scripts:
      - name: Flutter clean & get
        script: |
          set -euo pipefail
          flutter clean
          flutter pub get
      - name: Set iOS deployment target
        script: |
          set -euo pipefail
          sed -i '' "s/platform :ios, '[0-9.]*'/platform :ios, '15.0'/g" ios/Podfile 2>/dev/null || \
          sed -i "s/platform :ios, '[0-9.]*'/platform :ios, '15.0'/g" ios/Podfile
          
          if [ -f ios/Runner.xcodeproj/project.pbxproj ]; then
            sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj 2>/dev/null || \
            sed -i 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj
          fi
          
          echo "✅ iOS deployment target set to 15.0"
      - name: CocoaPods install
        script: |
          if [ ! -f ios/Flutter/Generated.xcconfig ]; then
            flutter pub get
          fi
          cd ios
          rm -rf Pods Podfile.lock .symlinks/
          pod repo update
          pod install --repo-update
      - name: Build unsigned IPA
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.pub-cache
        - ios/Pods
    artifacts:
      - build/ios/iphonesimulator/Runner.zip
      - build/ios/iphoneos/FlutterIpaExport.ipa