workflows:
  ios_appetize:
    name: iOS Appetize (Simulator)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.31.0
      xcode: 16.2
      vars:
        # Set APPETIZE_API_TOKEN securely in Codemagic UI (do not hardcode here)
        # APPETIZE_API_TOKEN should be set in the Codemagic UI environment variables, not here.
        APPETIZE_API_TOKEN: "REPLACE_WITH_YOUR_TOKEN" # <-- Remove this line or set a dummy value if required by schema
    scripts:
      - name: Install and pin Flutter SDK 3.31.0
        script: |
          set -euo pipefail
          FLUTTER_VERSION=3.31.0
          git clone --depth 1 -b ${FLUTTER_VERSION} https://github.com/flutter/flutter.git $CM_BUILD_DIR/flutter_${FLUTTER_VERSION}
          echo 'export PATH="$CM_BUILD_DIR/flutter_'${FLUTTER_VERSION}'/bin:$PATH"' >> $CM_ENV
          # Pre-warm Flutter tool
          export PATH="$CM_BUILD_DIR/flutter_${FLUTTER_VERSION}/bin:$PATH"
          flutter --version
          dart --version
      - name: Show Flutter/Dart versions
        script: |
          flutter --version
          dart --version
      - name: Flutter pub get
        script: flutter pub get
      - name: Update CocoaPods and install
        script: |
          cd ios
          pod repo update
          pod install
      - name: Build iOS simulator app (no signing required)
        script: flutter build ios --debug --simulator
      - name: Zip Runner.app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app
      - name: Upload to Appetize.io
        script: |
          if [ -z "$APPETIZE_API_TOKEN" ]; then
            echo "APPETIZE_API_TOKEN is not set in Codemagic environment" >&2
            exit 1
          fi
          RESPONSE=$(curl -s -X POST https://api.appetize.io/v1/apps \
            -u "$APPETIZE_API_TOKEN:" \
            -F "platform=ios" \
            -F "file=@build/ios/iphonesimulator/Runner.zip")
          echo "Appetize response: $RESPONSE"
          PUBLIC_URL=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('publicUrl',''))")
          if [ -z "$PUBLIC_URL" ] || [ "$PUBLIC_URL" = "null" ]; then
            echo "Failed to parse publicUrl from Appetize response" >&2
            exit 1
          fi
          echo "PUBLIC_URL=$PUBLIC_URL" >> $CM_ENV
          echo "Appetize public URL: $PUBLIC_URL"
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - build/ios/iphonesimulator/Runner.zip

  ios_ipa_unsigned:
    name: iOS IPA (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.31.0
      xcode: 16.2
    scripts:
      - name: Install and pin Flutter SDK 3.31.0
        script: |
          set -euo pipefail
          FLUTTER_VERSION=3.31.0
          git clone --depth 1 -b ${FLUTTER_VERSION} https://github.com/flutter/flutter.git $CM_BUILD_DIR/flutter_${FLUTTER_VERSION}
          echo 'export PATH="$CM_BUILD_DIR/flutter_'${FLUTTER_VERSION}'/bin:$PATH"' >> $CM_ENV
          export PATH="$CM_BUILD_DIR/flutter_${FLUTTER_VERSION}/bin:$PATH"
          flutter --version
          dart --version
      - name: Show Flutter/Dart versions
        script: |
          flutter --version
          dart --version
      - name: Flutter pub get
        script: flutter pub get
      - name: Update CocoaPods and install
        script: |
          cd ios
          pod repo update
          pod install
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Package IPA (unsigned)
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload
    artifacts:
      - build/ios/iphoneos/FlutterIpaExport.ipa

