// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFhlwpe8_nwoRejZSmWUNq6sYSL_heyQ',
    appId: '1:187048592726:web:34d266cdb991ecb89402f7',
    messagingSenderId: '187048592726',
    projectId: 'tionova-c566b',
    authDomain: 'tionova-c566b.firebaseapp.com',
    storageBucket: 'tionova-c566b.firebasestorage.app',
    measurementId: 'G-QXM87T79Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YeKXSSo15C4zt7qCBjjp39hts6sQPB8',
    appId: '1:187048592726:android:24724b2055759ee39402f7',
    messagingSenderId: '187048592726',
    projectId: 'tionova-c566b',
    storageBucket: 'tionova-c566b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMlP1FKaG6Rr1TdnaqJe2am2JQvTgPbDo',
    appId: '1:187048592726:ios:b729badbcd887f4c9402f7',
    messagingSenderId: '187048592726',
    projectId: 'tionova-c566b',
    storageBucket: 'tionova-c566b.firebasestorage.app',
    iosBundleId: 'com.example.tionova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMlP1FKaG6Rr1TdnaqJe2am2JQvTgPbDo',
    appId: '1:187048592726:ios:b729badbcd887f4c9402f7',
    messagingSenderId: '187048592726',
    projectId: 'tionova-c566b',
    storageBucket: 'tionova-c566b.firebasestorage.app',
    iosBundleId: 'com.example.tionova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZFhlwpe8_nwoRejZSmWUNq6sYSL_heyQ',
    appId: '1:187048592726:web:b92dcc80485909799402f7',
    messagingSenderId: '187048592726',
    projectId: 'tionova-c566b',
    authDomain: 'tionova-c566b.firebaseapp.com',
    storageBucket: 'tionova-c566b.firebasestorage.app',
    measurementId: 'G-BW07DP1ZGK',
  );
}
