import 'package:flutter/material.dart';

class ChapterDetailAISummaryCard extends StatelessWidget {
  final bool isDesktop;
  final bool isLoading;
  final bool hasSummary;
  final VoidCallback onAction;
  final VoidCallback onDownload;

  const ChapterDetailAISummaryCard({
    super.key,
    required this.isDesktop,
    required this.isLoading,
    required this.hasSummary,
    required this.onAction,
    required this.onDownload,
  });

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    if (isDesktop) {
      return Container(
        padding: const EdgeInsets.all(28),
        decoration: BoxDecoration(
          color: colorScheme.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: colorScheme.outline, width: 1),
        ),
        child: Row(
          children: [
            _buildIconContainer(colorScheme, 64, 32),
            const SizedBox(width: 20),
            Expanded(child: _buildTextContent(colorScheme, 20, 14)),
            const SizedBox(width: 20),
            _buildButtons(colorScheme),
          ],
        ),
      );
    }

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: colorScheme.outline, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              _buildIconContainer(colorScheme, 48, 24),
              const SizedBox(width: 16),
              Expanded(child: _buildTitle(colorScheme, 18)),
            ],
          ),
          const SizedBox(height: 12),
          _buildSubtitle(colorScheme, 13),
          const SizedBox(height: 16),
          _buildButtons(colorScheme),
        ],
      ),
    );
  }

  Widget _buildIconContainer(
    ColorScheme colorScheme,
    double size,
    double iconSize,
  ) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: colorScheme.primaryContainer,
        borderRadius: BorderRadius.circular(size * 0.22),
      ),
      child: Icon(
        Icons.auto_awesome_rounded,
        color: colorScheme.primary,
        size: iconSize,
      ),
    );
  }

  Widget _buildTextContent(
    ColorScheme colorScheme,
    double titleSize,
    double subtitleSize,
  ) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildTitle(colorScheme, titleSize),
        const SizedBox(height: 6),
        _buildSubtitle(colorScheme, subtitleSize),
      ],
    );
  }

  Widget _buildTitle(ColorScheme colorScheme, double size) {
    return Text(
      'AI-Powered Summary',
      style: TextStyle(
        color: colorScheme.onSurface,
        fontSize: size,
        fontWeight: FontWeight.w600,
        letterSpacing: -0.3,
      ),
    );
  }

  Widget _buildSubtitle(ColorScheme colorScheme, double size) {
    return Text(
      'Get key points, definitions, practice questions, and quick reference cards generated by AI',
      style: TextStyle(
        color: colorScheme.onSurfaceVariant,
        fontSize: size,
        height: 1.5,
      ),
    );
  }

  Widget _buildButtons(ColorScheme colorScheme) {
    return Wrap(
      spacing: 12,
      runSpacing: 12,
      children: [
        ElevatedButton(
          onPressed: isLoading ? null : onAction,
          style: ElevatedButton.styleFrom(
            backgroundColor: colorScheme.primary,
            foregroundColor: colorScheme.onPrimary,
            elevation: 0,
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.auto_awesome_rounded, size: 18),
              const SizedBox(width: 8),
              Text(
                isLoading
                    ? 'Loading...'
                    : (hasSummary ? 'View Summary' : 'Generate Summary'),
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
        ),
        OutlinedButton(
          onPressed: onDownload,
          style: OutlinedButton.styleFrom(
            foregroundColor: colorScheme.onSurface,
            side: BorderSide(color: colorScheme.outline, width: 1),
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
          child: const Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.download_rounded, size: 18),
              const SizedBox(width: 8),
              Text(
                'Download',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
