import 'package:flutter/material.dart';

class ChapterDetailAISummaryCard extends StatefulWidget {
  final bool isDesktop;
  final bool isLoading;
  final bool hasSummary;
  final VoidCallback onAction;
  final VoidCallback onDownload;

  const ChapterDetailAISummaryCard({
    super.key,
    required this.isDesktop,
    required this.isLoading,
    required this.hasSummary,
    required this.onAction,
    required this.onDownload,
  });

  @override
  State<ChapterDetailAISummaryCard> createState() =>
      _ChapterDetailAISummaryCardState();
}

class _ChapterDetailAISummaryCardState
    extends State<ChapterDetailAISummaryCard> {
  bool _isHovered = false;

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return MouseRegion(
      onEnter: (_) => setState(() => _isHovered = true),
      onExit: (_) => setState(() => _isHovered = false),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: EdgeInsets.all(widget.isDesktop ? 28 : 20),
        decoration: BoxDecoration(
          color: colorScheme.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: _isHovered
                ? colorScheme.primary.withOpacity(0.5)
                : colorScheme.outline.withOpacity(0.5),
            width: _isHovered ? 1.5 : 1,
          ),
          boxShadow: [
            if (_isHovered)
              BoxShadow(
                color: colorScheme.primary.withOpacity(0.08),
                blurRadius: 20,
                offset: const Offset(0, 10),
              ),
          ],
        ),
        child: widget.isDesktop
            ? Row(
                children: [
                  _buildIconContainer(colorScheme, 64, 32),
                  const SizedBox(width: 20),
                  Expanded(child: _buildTextContent(colorScheme, 22, 14)),
                  const SizedBox(width: 20),
                  _buildButtons(colorScheme),
                ],
              )
            : Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      _buildIconContainer(colorScheme, 48, 24),
                      const SizedBox(width: 16),
                      Expanded(child: _buildTitle(colorScheme, 18)),
                    ],
                  ),
                  const SizedBox(height: 12),
                  _buildSubtitle(colorScheme, 13),
                  const SizedBox(height: 20),
                  _buildButtons(colorScheme),
                ],
              ),
      ),
    );
  }

  Widget _buildIconContainer(
    ColorScheme colorScheme,
    double size,
    double iconSize,
  ) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 200),
      width: size,
      height: size,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [colorScheme.primary, colorScheme.primary.withOpacity(0.8)],
        ),
        borderRadius: BorderRadius.circular(size * 0.25),
        boxShadow: [
          BoxShadow(
            color: colorScheme.primary.withOpacity(0.3),
            blurRadius: _isHovered ? 12 : 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Icon(
        Icons.auto_awesome_rounded,
        color: colorScheme.onPrimary,
        size: iconSize,
      ),
    );
  }

  Widget _buildTextContent(
    ColorScheme colorScheme,
    double titleSize,
    double subtitleSize,
  ) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildTitle(colorScheme, titleSize),
        const SizedBox(height: 8),
        _buildSubtitle(colorScheme, subtitleSize),
      ],
    );
  }

  Widget _buildTitle(ColorScheme colorScheme, double size) {
    return Text(
      'AI-Powered Summary',
      style: TextStyle(
        color: colorScheme.onSurface,
        fontSize: size,
        fontWeight: FontWeight.w700,
        letterSpacing: -0.5,
      ),
    );
  }

  Widget _buildSubtitle(ColorScheme colorScheme, double size) {
    return Text(
      'Get key points, definitions, practice questions, and quick reference cards generated by AI',
      style: TextStyle(
        color: colorScheme.onSurfaceVariant,
        fontSize: size,
        height: 1.6,
      ),
    );
  }

  Widget _buildButtons(ColorScheme colorScheme) {
    return Wrap(
      spacing: 12,
      runSpacing: 12,
      children: [
        AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          child: ElevatedButton(
            onPressed: widget.isLoading ? null : widget.onAction,
            style: ElevatedButton.styleFrom(
              backgroundColor: colorScheme.primary,
              foregroundColor: colorScheme.onPrimary,
              elevation: _isHovered ? 4 : 0,
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                if (widget.isLoading) ...[
                  const SizedBox(
                    width: 16,
                    height: 16,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                    ),
                  ),
                  const SizedBox(width: 10),
                ] else
                  const Icon(Icons.auto_awesome_rounded, size: 20),
                const SizedBox(width: 8),
                Text(
                  widget.isLoading
                      ? 'Generating...'
                      : (widget.hasSummary
                            ? 'View Summary'
                            : 'Generate Summary'),
                  style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
          ),
        ),
        OutlinedButton(
          onPressed: widget.onDownload,
          style: OutlinedButton.styleFrom(
            foregroundColor: colorScheme.onSurface,
            side: BorderSide(
              color: _isHovered
                  ? colorScheme.primary.withOpacity(0.5)
                  : colorScheme.outline,
              width: 1.5,
            ),
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            backgroundColor: _isHovered
                ? colorScheme.primary.withOpacity(0.05)
                : Colors.transparent,
          ),
          child: const Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.download_rounded, size: 20),
              const SizedBox(width: 8),
              Text(
                'Download',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
